### ISSUE TITLE
Apple silicon support?

### ISSUE THREAD

**Issue by gingerbeardman** [TheSecEng/Alfred-Man#1]
Would be cool to get a Universal build for native Apple silicon support.

Thanks

**Comment by gingerbeardman** [comment]
I tried to do this myself but having never compiled any Go i was a bit lost.

**Comment by TheSecEng** [comment]
Do you use the PDF or HTML feature? I am thinking of removing those

**Comment by TheSecEng** [comment]
@gingerbeardman Please let me know if the latest release works

**Comment by gingerbeardman** [comment]
Works great! Thanks.

I don't think I've ever used the PDF or HTML output options.
